name: run-tests

on: [push, pull_request]

env:
  COMPOSER_ROOT_VERSION: 1.99

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.1", "8.2"]
          - "8.1"
          - "8.2"

        dependencies:
          - "highest"

    name: P${{ matrix.php-version }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: xdebug
          ini-values: zend.assertions=1

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --no-interaction --no-progress --prefer-lowest

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress

      - name: Run tests
        timeout-minutes: 3
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: coverage.svg
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
